
name: upload fork pr files
on:
  pull_request:
    types: [labeled]

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: console files
        run: ls

      - name: save fork pr files
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo $PR_NUMBER > ./pr_number
          
      - uses: actions/upload-artifact@v3
        with:
          name: pr_files
          path: ./       


